# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
        backend "azurerm" {
        resource_group_name  = "tfstate"
        storage_account_name = "tfstate1782876454"
        container_name       = "tfstate"
        key                  = "./terraform.tfstate"
        }
    }

